### ISSUE TITLE
Cannot find module './lib/aws'

### ISSUE THREAD

**Issue by nathaniela** [blmr/aws-elb-logs-to-elasticsearch#1]
Keep getting the following error when testing the lambda function.

{
  "errorMessage": "Cannot find module './lib/aws'",
  "errorType": "Error",
  "stackTrace": [
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}

**Comment by blmr** [comment]
Maka sure you are executing 'npm instal' before creating a lambda zip package and include 'node-modules' directory in your .zip
Also, you may try changing the 'aws-sdk'  version in package.json to a newer one.

**Comment by nathaniela** [comment]
I used version 2.28.0 and still i have the same issue.

START RequestId: e0236c8d-0cae-11e7-a5bf-7bfbfb7ff1a0 Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/task/node_modules/aws-sdk/index.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
END RequestId: e0236c8d-0cae-11e7-a5bf-7bfbfb7ff1a0
REPORT RequestId: e0236c8d-0cae-11e7-a5bf-7bfbfb7ff1a0	Duration: 45.29 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 7 MB

**Comment by blmr** [comment]
That's not the same issue anymore. Try replacing aws sdk version with "*". Could you upload your lambda package somewhere so I can take a look? Don't forget to remove any credentials or ES endpoint from it.  I will be able check it on Monday.

**Comment by AlanKK** [comment]
Did you find a solution?  I have the same error.
