### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by wansatriaandanu** [blmr/aws-elb-logs-to-elasticsearch#2]
**My Event** 
```
{
    "Event source type": "S3",
    "Bucket": "log-elb-mokapos-rails",
    "Event type": "Object Created (All)",
    "Prefix": "mokapos-rails-dev/AWSLogs/055378290905/elasticloadbalancing/ap-southeast-1/",
    "Suffix": ".log"
}
```

**I try print the event.Records**
`2017-11-02T10:42:49.037Z	91dbc1aa-bfba-11e7-a8a0-4b2dc3855808	undefined`

**I try print the envet.Prefix and the data will showup**
`2017-11-02T10:42:49.074Z	91dbc1aa-bfba-11e7-a8a0-4b2dc3855808	mokapos-rails-dev/AWSLogs/055378290905/elasticloadbalancing/ap-southeast-1/`

**The data can't parse because undefined**
```
2017-11-02T10:42:49.076Z	91dbc1aa-bfba-11e7-a8a0-4b2dc3855808	TypeError: Cannot read property 'forEach' of undefined at exports.handler (/var/task/index.js:138:18)
2017-11-02T10:42:49.076Z	91dbc1aa-bfba-11e7-a8a0-4b2dc3855808	TypeError: Cannot read property 'forEach' of undefined
at exports.handler (/var/task/index.js:138:18)
```

did i miss the step ?

**Comment by wansatriaandanu** [comment]
Solved
