### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined in node-elb-log-parser

### ISSUE THREAD

**Issue by neillturner** [blmr/aws-elb-logs-to-elasticsearch#5]
This is a problem in the dependency nodejs module  node-elb-log-parser not in the code here but documenting for anyone else who hits this issue: 
 
If you get this error : 
TypeError: Cannot read property 'split' of undefined
at module.exports (/var/task/node_modules/elb-log-parser/index.js:69:45)
at Transform.recordStream._transform (/var/task/index.js:148:25)
at Transform._read (_stream_transform.js:186:10)
at Transform._write (_stream_transform.js:174:12)
at doWrite (_stream_writable.js:397:12)
at writeOrBuffer (_stream_writable.js:383:5)
at Transform.Writable.write (_stream_writable.js:290:11)
at LineStream.ondata (_stream_readable.js:639:20)
at emitOne (events.js:116:13)
at LineStream.emit (events.js:211:7)

This see this pull request 
https://github.com/toshihirock/node-elb-log-parser/pull/7

**Comment by neillturner** [comment]
closing as just for info
